ARG BUILD_FROM=ghcr.io/coollabsio/coolify:latest
FROM ${BUILD_FROM}

# Expose ports
EXPOSE 8000 6001 6002

# Labels
LABEL \
    io.hass.name="Coolify" \
    io.hass.description="Self-hosting with superpowers" \
    io.hass.arch="aarch64|amd64" \
    io.hass.type="addon" \
    io.hass.version="4.0.0"
